name: ramses-env
channels:
  - conda-forge
dependencies:
  - pkg-config
  - gfortran
  - clang
  - llvm-openmp
#  - gcc_linux-64=12.*
#  - gxx_linux-64=12.*
  - openmpi
  - make
  - cmake
  - git
  - python=3.12
  - pip
  - numpy
  - astropy
  - matplotlib
  - jupyter
  - scipy
  - f90nml
  - yt
  - fftw
  - gsl



