name: ramses-env
channels:
  - conda-forge
dependencies:
  - gfortran
  - clang_osx-64=12.*     ## latest versions of C++ compilers do not work with MUSIC 
  - clangxx_osx-64=12.*  
#  - gcc_linux-64=12.*
#  - gxx_linux-64=12.*
  - openmpi
  - make
  - cmake
  - git
  - python=3.12
  - pip
  - numpy
  - astropy
  - matplotlib
  - jupyter
  - scipy
  - f90nml
  - yt
  - fftw
  - gsl



